package com.ram.buspass.features.helper.resource.remote.api


import com.ram.buspass.features.helper.resource.remote.api.model.ResponsePojo
import com.ram.buspass.features.helper.resource.remote.api.model.login.LoginPojo
import com.ram.buspass.features.helper.resource.remote.api.model.ticketBook.TicketBookPojo
import com.ram.buspass.features.login.domain.LoginUserModelDAO
import com.ram.buspass.features.register.domain.UserModelDAO
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST
import retrofit2.http.Query

interface ApiService {

//    @POST(END_POINTS_AUTH)
//    suspend fun getUser(@Body userDetails: UserDetails): LoginPojos?

    @POST("api/register/user/")
    suspend fun registerUser(
        @Body userModelDAO: UserModelDAO
    ): ResponsePojo?

    @POST("api/loginuser/")
    suspend fun loginUser(
        @Body loginUserModelDAO: LoginUserModelDAO
    ): LoginPojo?

    @GET("api/ticket/bus/")
    suspend fun getBookTicket(
        @Query("bus_id") id: Int?
    ): TicketBookPojo


//    @Headers("Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk5MTA2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Im5pa2VuLm1haGFyamFuK25tc3RzdHVkQGlubm92YXRldGVjaC5jbyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im5pa2VuLm1haGFyamFuK25tc3RzdHVkQGlubm92YXRldGVjaC5jbyIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiQUVPVUVBREVJUUtJN1hQWTVCRTNBVlQ3WUhLSzQySVAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiaHR0cDovL3d3dy5hc3BuZXRib2lsZXJwbGF0ZS5jb20vaWRlbnRpdHkvY2xhaW1zL3RlbmFudElkIjoiMSIsInN1YiI6Ijk5MTA2IiwianRpIjoiYWI3ZDUyZTMtNjc0Mi00MzE3LWI3NzYtN2IxMTBiM2ZiZmUyIiwiaWF0IjoxNjk1Nzk0MDI3LCJuYmYiOjE2OTU3OTQwMjcsImV4cCI6MTY5NzAwMzYyNywiaXNzIjoiQVBvbGxvIiwiYXVkIjoiQVBvbGxvIn0.uDkpnUQ04_dcuztmexbBm-0fEQdeOmtg9z4BoUvBGF4")
//    @GET(ENDPOINTS)
//    suspend fun getSubject(): SubjectsPojo
////    @Headers("Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk5MTA2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Im5pa2VuLm1haGFyamFuK25tc3RzdHVkQGlubm92YXRldGVjaC5jbyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im5pa2VuLm1haGFyamFuK25tc3RzdHVkQGlubm92YXRldGVjaC5jbyIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiQUVPVUVBREVJUUtJN1hQWTVCRTNBVlQ3WUhLSzQySVAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiaHR0cDovL3d3dy5hc3BuZXRib2lsZXJwbGF0ZS5jb20vaWRlbnRpdHkvY2xhaW1zL3RlbmFudElkIjoiMSIsInN1YiI6Ijk5MTA2IiwianRpIjoiYWI3ZDUyZTMtNjc0Mi00MzE3LWI3NzYtN2IxMTBiM2ZiZmUyIiwiaWF0IjoxNjk1Nzk0MDI3LCJuYmYiOjE2OTU3OTQwMjcsImV4cCI6MTY5NzAwMzYyNywiaXNzIjoiQVBvbGxvIiwiYXVkIjoiQVBvbGxvIn0.uDkpnUQ04_dcuztmexbBm-0fEQdeOmtg9z4BoUvBGF4")
//    @GET(SUBJECT_CONTENET_ENDS_POINTS)
//    suspend fun getVideoUrl(@Path("videoId") videoId: Int?): VideoUrlPojo //157
//
////    @Headers("Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk5MTA2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Im5pa2VuLm1haGFyamFuK25tc3RzdHVkQGlubm92YXRldGVjaC5jbyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im5pa2VuLm1haGFyamFuK25tc3RzdHVkQGlubm92YXRldGVjaC5jbyIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiQUVPVUVBREVJUUtJN1hQWTVCRTNBVlQ3WUhLSzQySVAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiaHR0cDovL3d3dy5hc3BuZXRib2lsZXJwbGF0ZS5jb20vaWRlbnRpdHkvY2xhaW1zL3RlbmFudElkIjoiMSIsInN1YiI6Ijk5MTA2IiwianRpIjoiZDU2YTg5NGEtYzdhMC00NDg3LWI5NmYtNDYwODFhOGYwYTE4IiwiaWF0IjoxNjk1NzIxODA1LCJuYmYiOjE2OTU3MjE4MDUsImV4cCI6MTY5NjkzMTQwNSwiaXNzIjoiQVBvbGxvIiwiYXVkIjoiQVBvbGxvIn0.NelRYQAMGDWl_kqwWfuphGvRsjaKYLkVtbAwca_P8IY")
//    @GET(VIDEO_ENDS)
//    suspend fun getVideoData(): VideoDataPojo?
////    @Headers("Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk5MTA2IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Im5pa2VuLm1haGFyamFuK25tc3RzdHVkQGlubm92YXRldGVjaC5jbyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im5pa2VuLm1haGFyamFuK25tc3RzdHVkQGlubm92YXRldGVjaC5jbyIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiQUVPVUVBREVJUUtJN1hQWTVCRTNBVlQ3WUhLSzQySVAiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiaHR0cDovL3d3dy5hc3BuZXRib2lsZXJwbGF0ZS5jb20vaWRlbnRpdHkvY2xhaW1zL3RlbmFudElkIjoiMSIsInN1YiI6Ijk5MTA2IiwianRpIjoiZDU2YTg5NGEtYzdhMC00NDg3LWI5NmYtNDYwODFhOGYwYTE4IiwiaWF0IjoxNjk1NzIxODA1LCJuYmYiOjE2OTU3MjE4MDUsImV4cCI6MTY5NjkzMTQwNSwiaXNzIjoiQVBvbGxvIiwiYXVkIjoiQVBvbGxvIn0.NelRYQAMGDWl_kqwWfuphGvRsjaKYLkVtbAwca_P8IY")
//    @GET(PROFILE_ENDS_POINTS)
//    suspend fun getProfile(): UsersPojo?


}